// This file is automatically generated. Do not edit it directly.
// REFACTOR: Redirecting to the singleton instance to prevent "Multiple GoTrueClient instances" error.

import { supabase as supabaseSingleton } from '@/lib/supabase';

export const supabase = supabaseSingleton;